# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: refactoring

    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '15' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: Grant execute permission for gradle wrapper
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test